language: node_js
node_js:
  - 'lts/*' # Latest LTS version of NodeJs
install:
  - npm install
script:
  - npm run build:prod
  - npm run test
cache: # Retrieve modules from cache and update when something changes
  directories:
    - 'node_modules'
notifications:
  email:
    on_success: always
    on_failure: always
